import "server-only";

/**
 * Image upload validation. The declared MIME type and filename from the
 * browser are never trusted: the real type is sniffed from magic bytes and
 * the stored filename is generated by us.
 */

export const MAX_IMAGE_BYTES = 5 * 1024 * 1024; // 5 MB

export interface SniffedImage {
  mimeType: "image/jpeg" | "image/png" | "image/webp" | "image/avif";
  extension: "jpg" | "png" | "webp" | "avif";
}

function startsWith(bytes: Uint8Array, signature: number[], offset = 0) {
  return signature.every((byte, index) => bytes[offset + index] === byte);
}

function ascii(bytes: Uint8Array, offset: number, length: number) {
  return String.fromCharCode(...bytes.slice(offset, offset + length));
}

/** Identify a supported image by content, or null when unsupported. */
export function sniffImage(bytes: Uint8Array): SniffedImage | null {
  if (bytes.length < 16) return null;

  // JPEG: FF D8 FF
  if (startsWith(bytes, [0xff, 0xd8, 0xff])) {
    return { mimeType: "image/jpeg", extension: "jpg" };
  }
  // PNG: 89 50 4E 47 0D 0A 1A 0A
  if (startsWith(bytes, [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])) {
    return { mimeType: "image/png", extension: "png" };
  }
  // WEBP: "RIFF" .... "WEBP"
  if (ascii(bytes, 0, 4) === "RIFF" && ascii(bytes, 8, 4) === "WEBP") {
    return { mimeType: "image/webp", extension: "webp" };
  }
  // AVIF: box "ftyp" with an AVIF brand
  if (ascii(bytes, 4, 4) === "ftyp") {
    const brand = ascii(bytes, 8, 4);
    if (brand === "avif" || brand === "avis") {
      return { mimeType: "image/avif", extension: "avif" };
    }
  }
  return null;
}

export interface ImageValidationError {
  message: string;
}

/** Validate size + real content type. Returns the sniffed type or an error. */
export function validateImage(
  bytes: Uint8Array,
): { ok: true; image: SniffedImage } | { ok: false; error: string } {
  if (bytes.length === 0) {
    return { ok: false, error: "The file is empty." };
  }
  if (bytes.length > MAX_IMAGE_BYTES) {
    return {
      ok: false,
      error: `Images must be ${MAX_IMAGE_BYTES / 1024 / 1024} MB or smaller.`,
    };
  }
  const image = sniffImage(bytes);
  if (!image) {
    return {
      ok: false,
      error: "Unsupported file. Upload a JPEG, PNG, WebP or AVIF image.",
    };
  }
  return { ok: true, image };
}
