import "server-only";
import { mkdir, readFile, unlink, writeFile } from "fs/promises";
import path from "path";

/**
 * Media storage abstraction. Product media reference an opaque
 * `storageKey`, never a filesystem path, so local disk today can be
 * swapped for object storage later without touching the catalog model.
 */

export interface StorageProvider {
  put(key: string, data: Buffer): Promise<void>;
  read(key: string): Promise<Buffer>;
  delete(key: string): Promise<void>;
}

/**
 * Storage keys are generated by this app (uuid + extension) and never
 * derived from user input. This guard is the last line of defence against
 * path traversal if a key ever reaches storage from elsewhere.
 */
const KEY_PATTERN = /^[a-f0-9-]{36}\.[a-z0-9]{2,5}$/;

export function assertSafeKey(key: string): void {
  if (!KEY_PATTERN.test(key)) {
    throw new Error("Unsafe storage key rejected.");
  }
}

const MEDIA_DIR = path.join(process.cwd(), ".data", "media");

const localProvider: StorageProvider = {
  async put(key, data) {
    assertSafeKey(key);
    await mkdir(MEDIA_DIR, { recursive: true });
    await writeFile(path.join(MEDIA_DIR, key), data);
  },
  async read(key) {
    assertSafeKey(key);
    return readFile(path.join(MEDIA_DIR, key));
  },
  async delete(key) {
    assertSafeKey(key);
    await unlink(path.join(MEDIA_DIR, key)).catch(() => {
      // Already gone — deleting media should stay idempotent.
    });
  },
};

export function getStorageProvider(): StorageProvider {
  // Later: switch on a STORAGE_PROVIDER env var (s3, blob, …).
  return localProvider;
}
